### ISSUE TITLE
Please submit tree-sitter queries to nvim-treesitter

### ISSUE THREAD

**Issue by cpkio** [pfeiferj/tree-sitter-hurl#2]
So they would be added to repo and grammar listed in the docs.

**Comment by pfeiferj** [comment]
I'll look into it when I get a chance. I think there's probably enough interest for it to be worth it

**Comment by pfeiferj** [comment]
Ok, so it seems there's two parts to this. We need both filetype detection in neovim and to get the grammar added to the nvim-treesitter repo.

Filetype detection:
The process to get filetype detection added to neovim is to first get support upstreamed into vim itself then the neovim team will port it to neovim. The vim pr can be tracked here: https://github.com/vim/vim/pull/12631

nvim-treesitter:
I've gone ahead and created a pr but I'm not sure if the filetype detection is a pre-requisite. The pr can be tracked here: https://github.com/nvim-treesitter/nvim-treesitter/pull/5065

**Comment by cpkio** [comment]
IMO filetype detection is not needed: there's no convention of file extension for Hurl files, so each user should do it by himself according to extension or naming he uses.

**Comment by pfeiferj** [comment]
> IMO filetype detection is not needed: there's no convention of file extension for Hurl files, so each user should do it by himself according to extension or naming he uses.

The docs explicitly say the extension is .hurl
