### ISSUE TITLE
problem configuring hurl lsp

### ISSUE THREAD

**Issue by bolanosdev** [pfeiferj/tree-sitter-hurl#7]
hi Jacob

thanks for creating this parsers.
I was trying to import it into a brand new lazy vim configuration but for some reason I don't see it working.

mvim-hurl works nicely to execute hurl requests with key bindings but I can't make the lsp work, wondering if you could help.
![Screenshot 2024-01-31 at 1 33 12 PM](https://github.com/pfeiferj/tree-sitter-hurl/assets/2865089/a811c1ec-58c1-43e3-b4a9-45bd3f708702)

**Comment by bolanosdev** [comment]
I think I was able to figure out how to sett up for lazy.

![Screenshot 2024-01-31 at 1 56 53 PM](https://github.com/pfeiferj/tree-sitter-hurl/assets/2865089/f7451d2d-b819-44b0-a786-47dbed99db3d)


in case you want to add it to the readme

```
return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      vim.list_extend(opts.ensure_installed, { "hurl" })
    end,
    requires = {
      {
        "pfeiferj/nvim-hurl",
        branch = "main",
      },
    },
    config = function(_, opts)
      opts.highlight = { enable = true }
      opts.indent = { enable = true }
      require("nvim-treesitter.configs").setup(opts)
    end,
  }
}
```

**Comment by pfeiferj** [comment]
@bolanosdev You shouldn't need to use the nvim-hurl plugin anymore. The parser is available in nvim-treesitter so you should be able to just do `:TSInstall hurl` to get highlighting. Latest versions of neovim should also auto detect .hurl files as the hurl file format. The only other thing the nvim-hurl plugin does is help to run hurl on the current file, but there's realistically better command runners out there
